### ISSUE TITLE
Please use constants

### ISSUE THREAD

**Issue by taveratch** [WuttipatNilsiri/StopWatch#5]
`return (System.nanoTime() - startTime)/(1000.0*1000.0*1000.0);`

Using 1000.0*1000.0*1000.0 is not wrong, but it's a bad practice. 

Consider this scenario, you finish this work and got back to read it after 1 year; will you be able to understand what it is. If your friend or another developer is reading this, will they be able to understand it too? 

On the other hand, if you define a constant and named it well, ex. NANOSECONDS. You can immediately understand what it is. This save yourself and other people the trouble of reading.

**Comment by WuttipatNilsiri** [comment]
done
