### ISSUE TITLE
Do not use static for class that have many instances

### ISSUE THREAD

**Issue by taveratch** [WuttipatNilsiri/StopWatch#6]
`static long endTime;`
`Stopwatch.isRunning()`
`public static  boolean isRunning()`

**Consider this scenario**
 You initialize 2 Stopwatch to measure 2 different things concurrently(in the same time, 2 threads) let's call them `sw1` and `sw2`. You start() `sw1` and stop(), then you start() `sw2`. 

You wanna know the elapsed time of 'sw1'. Now your `endTime` is 0(from start() setting `endTime = 0;`), so `Stopwatch.isRunning()` returns **true** you'll get this `return (System.nanoTime() - startTime)`
which is not the time you want, since 'sw1' has already stop

**When creating class that could have many instances, do not use static attributes that are shared among them, if any of them change the attribute values, it will affect all other instances.**

**Comment by WuttipatNilsiri** [comment]
done
